In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat


# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import logisticregression
# from sklearn.metrics impot classification_report,confusion_matrix

In [19]:
advertising = pd.read_csv('C:/Users/smit7/Downloads/advertising.csv')

In [20]:
advertising.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [21]:
advertising.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [22]:
advertising.describe()

Daily Time Spent on Site          Age   Area Income  \
count               1000.000000  1000.000000   1000.000000   
mean                  65.000200    36.009000  55000.000080   
std                   15.853615     8.785562  13414.634022   
min                   32.600000    19.000000  13996.500000   
25%                   51.360000    29.000000  47031.802500   
50%                   68.215000    35.000000  57012.300000   
75%                   78.547500    42.000000  65470.635000   
max                   91.430000    61.000000  79484.800000   

       Daily Internet Usage         Male  Clicked on Ad  
count           1000.000000  1000.000000     1000.00000  
mean             180.000100     0.481000        0.50000  
std               43.902339     0.499889        0.50025  
min              104.780000     0.000000        0.00000  
25%              138.830000     0.000000        0.00000  
50%              183.130000     0.000000        0.50000  
75%              218.792500     1.000000        1.00000  
max              269.960000     1.000000        1.00000

In [23]:
from sklearn.model_selection import train_test_split

In [25]:
x = advertising[['Daily Time Spent on Site','Area Income','Daily Internet Usage','Male']]
y = advertising['Clicked on Ad']

In [42]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33 , random_state=42)

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [50]:
prediction = logmodel.predict(x_test)

In [46]:
from sklearn.metrics import classification_report,confusion_matrix

In [54]:
print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       162
           1       0.97      0.93      0.95       168

    accuracy                           0.95       330
   macro avg       0.95      0.95      0.95       330
weighted avg       0.95      0.95      0.95       330

[[157   5]
 [ 12 156]]


In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
dtree = DecisionTreeClassifier()

In [57]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [58]:
predictiontree = dtree.predict(x_test)

In [61]:
print(classification_report(y_test,predictiontree))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93       162
           1       0.93      0.94      0.93       168

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330



In [63]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [64]:
predict_forest = rfc.predict(x_test)

In [65]:
print(classification_report(y_test,predict_forest))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94       162
           1       0.95      0.93      0.94       168

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



In [66]:
print(confusion_matrix(y_test,predict_forest))

[[154   8]
 [ 11 157]]


In [68]:
from sklearn.svm import SVC

In [72]:
model = SVC()

In [73]:
model.fit(x_train , y_train)

SVC()

In [74]:
predict_svm = model.predict(x_test)

In [76]:
print(confusion_matrix(y_test,predict_svm))

[[139  23]
 [ 80  88]]


In [79]:
from sklearn.naive_bayes import GaussianNB

In [80]:
naive_model=GaussianNB()

In [81]:
naive_model.fit(x_train,y_train)

GaussianNB()