In [5]:
import numpy as np

In [6]:
rarr=np.random.uniform(0,15,10)
rarr
                    

array([14.89753449,  6.65091309,  6.57947799,  5.43703285,  0.58151068,
        4.24853587,  0.96572639, 12.11410758, 10.879721  ,  6.31364802])

In [11]:
np.round(rarr,decimals=2)

array([14.9 ,  6.65,  6.58,  5.44,  0.58,  4.25,  0.97, 12.11, 10.88,
        6.31])

In [13]:
np.ceil(rarr)

array([15.,  7.,  7.,  6.,  1.,  5.,  1., 13., 11.,  7.])

In [14]:
np.floor(rarr)

array([14.,  6.,  6.,  5.,  0.,  4.,  0., 12., 10.,  6.])

In [16]:
mat=np.arange(0,25).reshape(5,5)

In [17]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
np.sum(mat,axis=0)

array([50, 55, 60, 65, 70])

In [20]:
np.min(mat,axis=0)

array([0, 1, 2, 3, 4])

In [21]:
np.max(mat,axis=0)

array([20, 21, 22, 23, 24])

In [23]:
np.var(mat,axis=0)

array([50., 50., 50., 50., 50.])

In [24]:
np.std(mat,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [25]:
nv=np.full(10,'NaN')

In [26]:
nv[5]=200

In [27]:
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', '200', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [32]:
hey=np.arange(100,150)
hey

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [33]:
np.flip(hey)

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [34]:
mat=np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
code=np.nonzero([1,0,2,5,8,0,0,9,0,])
code

(array([0, 2, 3, 4, 7], dtype=int64),)

In [39]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
m[::2,::2]=0
m[1::2,1::2]=0

NameError: name 'm' is not defined

In [1]:
import pandas as pd

product_ids = ["P001", "P002", "P003", "P004", "P005"]
product_names = ["Phone", "Tablet", "Watch", "Earbuds", "Speaker"]
product_prices = [499.99, 299.99, 199.99, 99.99, 79.99]

data = {
    "product_id": product_ids,
    "product_name": product_names,
    "product_price": product_prices
}

df = pd.DataFrame(data)

print(df)

  product_id product_name  product_price
0       P001        Phone         499.99
1       P002       Tablet         299.99
2       P003        Watch         199.99
3       P004      Earbuds          99.99
4       P005      Speaker          79.99


In [2]:
df['product_name'].loc[3]

'Earbuds'

In [3]:
df.loc[3]

product_id          P004
product_name     Earbuds
product_price      99.99
Name: 3, dtype: object